name: main

on: push

jobs:
  install:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [0.5.8, 0.6.0, 0.6.2, 0.6.7, 0.6.10, 0.6.12, 0.7.3, 0.8.1, 1.0.0, 1.0.10, 1.0.36, 1.1.3]
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.version }}
      - run: bun install
      - run: bun add redux
        working-directory: libs/api
